// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtVfTME_7TXVTfaKN5b2j6Zxx2Ce5E66E',
    appId: '1:280073223969:web:dedd72b2afb1732f228860',
    messagingSenderId: '280073223969',
    projectId: 'safe-c3a3d',
    authDomain: 'safe-c3a3d.firebaseapp.com',
    storageBucket: 'safe-c3a3d.firebasestorage.app',
    measurementId: 'G-NKHK8YH5BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbzNlc1QXtDEplMy7smX_gBDBJe9_F4A',
    appId: '1:280073223969:android:7f184ec94b1c83e2228860',
    messagingSenderId: '280073223969',
    projectId: 'safe-c3a3d',
    storageBucket: 'safe-c3a3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQxp2aSjFH_bcrx9qhxsN3o02--Rm_JRw',
    appId: '1:280073223969:ios:3939f81d44a53868228860',
    messagingSenderId: '280073223969',
    projectId: 'safe-c3a3d',
    storageBucket: 'safe-c3a3d.firebasestorage.app',
    iosBundleId: 'com.paulo.safe.maioamarelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQxp2aSjFH_bcrx9qhxsN3o02--Rm_JRw',
    appId: '1:280073223969:ios:6a7f36311a747a83228860',
    messagingSenderId: '280073223969',
    projectId: 'safe-c3a3d',
    storageBucket: 'safe-c3a3d.firebasestorage.app',
    iosBundleId: 'com.safe.safe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtVfTME_7TXVTfaKN5b2j6Zxx2Ce5E66E',
    appId: '1:280073223969:web:69123f08918bbdf5228860',
    messagingSenderId: '280073223969',
    projectId: 'safe-c3a3d',
    authDomain: 'safe-c3a3d.firebaseapp.com',
    storageBucket: 'safe-c3a3d.firebasestorage.app',
    measurementId: 'G-DV3KGW1M4G',
  );

}